# Generated by Django 5.0.5 on 2024-05-09 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Metric Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Duration (minutes)')),
                ('realtime_staus', models.BooleanField(default=True)),
                ('conditions', models.ManyToManyField(to='alerts.condition')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(default=list)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.metric')),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.metriccategory'),
        ),
    ]
