# Generated by Django 5.0.5 on 2024-05-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='realtime_staus',
            new_name='realtime_status',
        ),
    ]
