# Generated by Django 5.0.5 on 2024-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_realtime_staus_alert_realtime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='alert_description',
            field=models.CharField(default='hello', max_length=255, verbose_name='Alert Description'),
            preserve_default=False,
        ),
    ]
