# Generated by Django 5.0.5 on 2024-05-16 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
